name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: #[push]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      # A strategy is used to define a matrix of variations of the environment in which we run the job. For our job, we will use node version 16.
      matrix:
        node-version: [16.x]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
      - run: npm server
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: cuong2811
          password: 9%ZU7wpW8+KVJRm
      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
      - run: echo Build started on `date`
      - run: echo Building the Docker image...
      - run: docker build -t cuong2811/demo:latest .
      - run: echo Build completed on `date`
      - run: docker images
      - run: echo Pushing the Docker images...
      - run: docker push cuong2811/demo:latest
      - run: docker run -d -p 8080:80 cuong2811/demo:latest
      - run: docker ps
      
      
        

